# SPDX-FileCopyrightText: 2026 Ken Tobias
# SPDX-License-Identifier: GPL-3.0-only
#
# Homebrew formula for etr.
#
# THIS IS A TEMPLATE, NOT A PUBLISHABLE FORMULA.
# ----------------------------------------------
# The url and sha256 fields below are sentinels, filled in by `scripts/render_packaging.py`
# at publish time from the tag being released and the sha256 of the tarball actually
# downloaded.
# `just brew-publish <version>` renders it and pushes the *rendered* file to the tap at
# github.com/l1a/homebrew-etr. Nothing is hand-edited in the tap.
#
# It records no version, because recording one is what goes wrong: the sibling repo's
# `packaging/aur/PKGBUILD` was an inert "reference copy" that nothing rendered, published or
# checked, and it reached ELEVEN releases of drift while every CI run stayed green. A guard
# only ever detects a disagreement between two recordings of the same fact; writing the fact
# down once, at publish time, removes the disagreement instead.
#
# WHY A TAP RATHER THAN homebrew-core
# ------------------------------------
# homebrew-core has notability requirements this project does not meet yet. A tap needs no
# approval and is the realistic first step; moving to core later is a separate decision, not
# a prerequisite.
#
# WHY A SOURCE BUILD AND NOT A BOTTLE
# ------------------------------------
# A bottle is a prebuilt binary that CI must build, sign and upload per macOS version and
# architecture. This formula builds from source and needs only Rust, which Homebrew supplies
# as a build-time dependency. The trade is a slower first install against no new CI secrets
# and no release-asset plumbing. Revisit when install time is an actual complaint.
#
# BOTH BINARIES ARE INSTALLED, which is the etr-specific part of this file.
# `etrs` is Unix-only by design (it daemonises with fork/setsid) -- but macOS is Unix, so it
# builds and runs there. Only Windows is excluded, and Homebrew never targets it. Installing
# only the client would make `brew install etr` unable to host a session at all.
class Etr < Formula
  desc "Reconnecting remote shell over QUIC"
  homepage "https://github.com/l1a/etr"
  url "https://github.com/l1a/etr/archive/refs/tags/v0.9.3.tar.gz"
  sha256 "67b7e236e1bf4c14db1a63e96fefc92c3e685ffdc9622985bd7f2acc3a73d8a0"
  license "GPL-3.0-only"
  head "https://github.com/l1a/etr.git", branch: "main"

  depends_on "rust" => :build

  def install
    # `std_cargo_args` ALREADY passes `--locked` (along with `--root` and `--path`), so it
    # must not be repeated: cargo rejects a duplicate outright with
    # "the argument '--locked' cannot be used multiple times".
    #
    # `--locked` is load-bearing here for the same reason the COPR spec says never to drop
    # it: Homebrew builds with network access and no vendored dependencies, so Cargo.lock is
    # the only thing pinning resolution to what CI actually tested.
    #
    # This installs every [[bin]] in the manifest, which is both etr and etrs.
    system "cargo", "install", *std_cargo_args

    # Install the COMMITTED man pages rather than regenerating them. They are tracked
    # precisely so this tarball carries them; regenerating with mandown would make the
    # packaged page depend on which mandown build happened to run.
    man1.install "man/etr.1"
    man1.install "man/etrs.1"

    # Generated by the binaries that were just built, so completions cannot disagree with the
    # CLI they describe. `--completions=<shell>` is the flag's `=`-joined form, which is what
    # `shell_parameter_format` produces here.
    #
    # `shells:` is deliberately omitted: bash/zsh/fish is the default, and passing it
    # explicitly is flagged by `brew audit --strict` as redundant.
    generate_completions_from_executable(bin/"etr", shell_parameter_format: "--completions=")
    generate_completions_from_executable(bin/"etrs", shell_parameter_format: "--completions=")
  end

  test do
    # `--version` proves each binary runs and is the version the formula claims. BOTH are
    # checked: a formula that installed only the client would still pass a single-binary test
    # while leaving `brew install etr` unable to host a session.
    assert_match version.to_s, shell_output("#{bin}/etr --version")
    assert_match version.to_s, shell_output("#{bin}/etrs --version")

    # A target that cannot resolve must FAIL, and must fail with etr's own diagnostic rather
    # than a panic. This is the cheapest test that exercises real argument handling and the
    # error path without a network, an ssh daemon or a PTY -- all three of which a Homebrew
    # test machine lacks. `2>&1` because the diagnostic goes to stderr.
    output = shell_output("#{bin}/etr no-such-host.invalid true 2>&1", 1)
    refute_match(/panicked/, output)

    # The man pages must be installed and carry a real version footer -- a bare existence
    # check would pass on the `$DATE`/`$pkgver` placeholder defect the sibling repo's AUR
    # package shipped for months.
    assert_path_exists man1/"etr.1"
    assert_match "etr #{version}", (man1/"etr.1").read
    assert_path_exists man1/"etrs.1"
    assert_match "etr #{version}", (man1/"etrs.1").read
  end
end
